# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tatsuya Sato (satoryu)
email: satoryu.1981@gmail.com
logo: assets/img/profile.jpeg
google_analytics: UA-10079057-16

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://satoryu.github.io" # the base hostname & protocol for your site

## For SEO tags plugin
author: Tatsuya Sato
twitter:
  username: sato_ryu
  card: summary
social:
  name: Tatsuya Sato
  links:
    - https://twitter.com/sato_ryu
    - https://github.com/satoryu
    - https://www.linkedin.com/in/tatsuya-sato/
    - https://www.facebook.com/satoryu
    - https://satoryu.hatenablog.com/

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jemoji

theme: jekyll-theme-minimal
